### PR TITLE
Add Serilog with console sink to allow logging

### PR DESCRIPTION
**Pull request by uuksu**
- Added Serilog with console sink to allow logging (fix Issue #1)
- Added few log examples
- Fixed project not compiling due to renaming introduced in #14 

This is a pretty thin change but it enables logging and gives you an idea how to add more logging. If you already had something you wanted to be logged in your mind, just tell me and I can add more log lines!

### CODE REVIEW

**Review by hmumm — COMMENTED** [review]
The only other place I could see logging is logging every instruction run (probably at a lower level then information not sure what levels seriolog has). That would be in Chip8.EmulateCycle(). Other than that looks great!

**Comment by adamgauthier** [comment]
@uuksu Sorry about the compile error, I had renamed the Game class but reverted it last second because it wasn't detected as a git rename 😕 Thanks for fixing it!

**Comment by hmumm** [comment]
No that's my bad, actions should've caught that. It should in the future now with #16

**Comment by uuksu** [comment]
@louistio @hmumm No problem guys! I did not mean to blame anyone, I just find it good practise to point out in issue tracking where something breaks and when it's fixed :)

I added a one log line to log the current OpCode but I find it not that useful. I wrote my ideas to refactor the Chip8 class [here](https://github.com/hmumm/chip8emulator/issues/2#issuecomment-703223719). After the refactoring is done (what ever way it is done) then this logging could be expanded to be more usefull.

**Comment by hmumm** [comment]
Awesome that stuff looks good, I'll think about that when refactoring with delegates. For now I'll go ahead and merge this.

**Pull request merged**
